services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=BukyAccommodation'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=password'
    ports:
      - '5050:80'
    depends_on:
      - postgres