name: CI/CD
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: JDK Setup
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Deps
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('reservations-service/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build And Test
        run: |
          mvn clean install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/buky-reservations:latest .


      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.1.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: List Docker Images (Debug Purposes)
        run: docker images

      - name: Publish Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/buky-reservations:latest ${{ secrets.DOCKER_USERNAME }}/buky-reservations:${{ steps.versioning.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/buky-reservations:${{ steps.versioning.outputs.version }}


      - name: Create Release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          prerelease: true